# This file was generated by GoReleaser. DO NOT EDIT.
cask "autofix" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "80c3a3826abd7de8db94a26ecf72cf9fcbb16aedcebd4471794d084efb4ac08b"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a1f1c14f97b7117a92b0bfb03d74e29823ce2db7dec50e249281681d18c33d0"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc62dd215f0d83ded0ab5a05c724d97cd854ef13655400f8b7bcbea24d6ebfcb"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c806261035c796cc7d966c5e559f1477b4a50fa04ad6032274304ce3a368f3e9"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "autofix"
  desc "Behavioral attestation and AI-powered fixes for agent tools"
  homepage "https://github.com/trustabl/trustabl-probe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autofix"

  # No zap stanza required
end
