# This file was generated by GoReleaser. DO NOT EDIT.
cask "autofix" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "94f13ca348d60b55d7f31501e765c13a937405e42d74dc69b275a3cb4f490413"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "33ca514231a389a6711e6c1ce89c0d1733c1348ed77937396b6f4469fd12991c"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7a389c8574de57adeb47064d5386fc4677274bd420e57be995ffded588f65728"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e661ea4c20afaa7d446e012d4f6ecc5654ec1e516a49ea5ce7901bc2ffd98aed"
      url "https://github.com/trustabl/trustabl-probe/releases/download/v#{version}/autofix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "autofix"
  desc "Behavioral attestation and AI-powered fixes for agent tools"
  homepage "https://github.com/trustabl/trustabl-probe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autofix"

  # No zap stanza required
end
